backend:
  name: github
  repo: jorgeneidem/fuve-levelup-gatsby

media_folder: static/assets
public_folder: /assets

collections:
  - name: post
    label: Posts
    folder: src/posts
    create: true
    fields: 
      - { name: title, label: Title }
      - { name: date, label: Create At, widget: date }
      - { name: hero_image, label: Hero Image, widget: custompathimage, customMediaPath: ../assets/, rawMediaPath: https://raw.githubusercontent.com/jorgeneidem/fuve-levelup-gatsby/static/assets/ }
      - { name: body, label: Post, widget: markdown } 
    


