backend:
  name: github
  repo: jorgeneidem/fuve-levelup-gatsby

media_folder: static/assets
public_folder: /assets

collections:
  - name: post
    label: Posts
    folder: src/posts
    create: true
    fields: 
      - { name: title, label: Title }
      - { name: date, label: Create At, widget: date }
      - { name: cover_image, label: Cover Image, widget: image } 
      - { name: body, label: Post, widget: markdown } 
    


