backend:
  name: github
  repo: jorgeneidem/fuve-levelup-gatsby

media_folder: src/posts
public_folder: ../

collections:
  - name: post
    label: Posts
    folder: src/posts
    create: true
    fields: 
      - { name: title, label: Title }
      - { name: date, label: Create At, widget: date }
      - { name: hero_image, label: Hero Image, widget: image } 
      - { name: body, label: Post, widget: markdown } 
    


